---
#--------------------------------------------
# General Site Settings

# Personal info
name: Your Name
title: Your job title
email: Your email (optional)
phone: Your phone number (optional)
website: Your website (eg. https://google.com)(optional)

#About Info

about_title: About Me # (Use this to override about section title)
profile_image: #Directory of profile image (eg. images/profile.jpg)
content: | # this will include new lines to allow paragraphs
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
    - Lists
    - Tables
    - <a href="google.com">Links</a>
    - Images
